version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: amrutam
      POSTGRES_PASSWORD: amrutam
      POSTGRES_DB: amrutam
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amrutam"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  app:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql://amrutam:amrutam@postgres:5432/amrutam
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    ports: ["3000:3000"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    command: ["node", "dist/worker.js"]
    env_file: .env
    environment:
      DATABASE_URL: postgresql://amrutam:amrutam@postgres:5432/amrutam
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    volumes: ["./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - "./infra/grafana/provisioning:/etc/grafana/provisioning"
      - "./infra/grafana/dashboards:/etc/grafana/provisioning/dashboards/files"
    ports: ["3001:3000"]
    depends_on: [prometheus, loki, jaeger]

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/loki-config.yml"]
    volumes: ["./infra/loki/loki-config.yml:/etc/loki/loki-config.yml"]
    ports: ["3100:3100"]

  promtail:
    image: grafana/promtail:latest
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    volumes:
      - "./infra/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on: [loki]

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4318:4318"

volumes:
  pgdata:
